modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "xeno_early_start"
version = "${version}"
displayName = "Xenonomous' Early Start"
authors = "Me!"
description = '''
An overhaul of the early game progression, It also brings copper equipment to 1.20.1 (that actually look good) which fits nicely!
'''
#logoFile = ""

[[dependencies.xeno_early_start]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.xeno_early_start]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.xeno_early_start]]
modId = "cloth_config"
mandatory = true
versionRange = "[11.1.136,)"
ordering = "AFTER"
side = "BOTH"